services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gym_db
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gym_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: trainer_workload_db
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  activemq:
    image: apache/activemq-classic:6.1.3
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - activemqdata:/opt/apache-activemq/data
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsu admin:admin http://localhost:8161/admin/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-discovery-server:
    build: ./discovery-server
    container_name: eureka-discovery-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 20s
      timeout: 5s
      retries: 5

  trainer-workload-service:
    build: ./trainer-workload-service
    container_name: trainer-workload-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongo:27017/trainer_workload_db?authSource=admin
      ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
      EUREKA_URI: http://eureka-discovery-server:8761/eureka
      JWT_SECRET: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
    depends_on:
      activemq:
        condition: service_healthy
      eureka-discovery-server:
        condition: service_healthy
      mongo:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 20s
      timeout: 5s
      retries: 5

  gym-application:
    build: .
    container_name: gym-application
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://db:5432/gym_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
      EUREKA_URI: http://eureka-discovery-server:8761/eureka
      JWT_SECRET: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
    depends_on:
      db:
        condition: service_healthy
      activemq:
        condition: service_healthy
      eureka-discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 20s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  activemqdata:
  mongodata: