eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/gym_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    user: postgres
    password: postgres

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

messaging:
  queues:
    trainer-workload: trainer.workload.queue

security:
  jwt:
    secret: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
    expiration-minutes: 60
    service-token-expiration-minutes: 5

  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173

logging:
  level:
    root: INFO
    ua.ivan.epam.gym.application: DEBUG
    org.hibernate.SQL: DEBUG