storage.init.users.path=data/users.txt
storage.init.trainers.path=data/trainers.txt
storage.init.trainees.path=data/trainees.txt
storage.init.trainings.path=data/trainings.txt
storage.init.training-types.path=data/training-types.txt