storage.init.users.path=data/users.txt
storage.init.trainers.path=data/trainers.txt
storage.init.trainees.path=data/trainees.txt
storage.init.trainings.path=data/trainings.txt
storage.init.training-types.path=data/training-types.txt

db.url=jdbc:postgresql://localhost:5431/gym_db
db.username=postgres
db.password=postgres
db.driver-class-name=org.postgresql.Driver

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true