eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    preferIpAddress: true

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}


logging:
  level:
    root: INFO
    ua.ivan.epam.gym.application: INFO
    org.hibernate.SQL: WARN

management:
  endpoint:
    health:
      show-details: when-authorized