eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    preferIpAddress: true

security:
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    root: INFO
    ua.ivan.epam.gym.application: INFO
    org.hibernate.SQL: WARN

management:
  endpoint:
    health:
      show-details: when-authorized