security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES}

logging:
  level:
    root: WARN
    ua.ivan.epam.gym.application: INFO
    org.hibernate.SQL: OFF

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: never