eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    preferIpAddress: true

security:
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    root: WARN
    ua.ivan.epam.gym.application: INFO
    org.hibernate.SQL: OFF

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: never