eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

security:
  jwt:
    secret: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=

logging:
  level:
    root: INFO
    ua.ivan.epam.gym.workload: DEBUG
    org.hibernate.SQL: DEBUG