eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    preferIpAddress: true

spring:
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

security:
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    root: INFO
    ua.ivan.epam.gym.application: INFO
    org.hibernate.SQL: WARN

management:
  endpoint:
    health:
      show-details: when-authorized