server:
  port: 8081

spring:
  application:
    name: trainer-workload-service

messaging:
  queues:
    trainer-workload: trainer.workload.queue
  listener:
    trainer-workload:
      concurrency: 1-5

security:
  jwt:
    secret: ${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true